blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views
app_name = "blog"
urlpatterns = [
    url(r'^$', views.index,name="initial_home"),
    # url(r'^(?P<tt>\W{0,50})/(?P<id>\d+)', views.detail_blog,name="home"),
    url(r'^(?P<tt>[\w-]+)/(?P<id>\d+)', views.detail_blog,name="home"),
]

ico_proj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('main.urls')),
    url(r'^blog/',include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views
app_name = "main"
urlpatterns = [
    url(r'^$', views.index,name="home"),
    url(r'^detail/(?P<category>\w{0,50})/(?P<name>\w{0,50})/',views.ico_detail,name = "detail"),
    url(r'^category/(?P<category>\w{0,50})/',views.show_by_category,name="category"),
    url(r'^search/',views.search_ico,name="search"),
    url(r'^about/',views.about,name="about"),
    url(r'^adver/',views.adver,name="adver"),
    url(r'^news/',views.news,name="news"),
]

blog/models.py
from django.db import models
import datetime
# Create your models here.
from froala_editor.fields import FroalaField
class News(models.Model):
	class Meta:
		verbose_name_plural = "News"
	author_image = models.FileField(verbose_name = "Author Image ",upload_to='News/Author')
	author_name = models.CharField(verbose_name = "Author Name",max_length=50)
	title = models.CharField(verbose_name="Title",max_length = 100)
	photo = models.FileField(upload_to='News/Photo',blank=True, null=True)
	movie_url = models.CharField(max_length = 100,blank=True, null=True)
	sponsor = models.CharField(verbose_name="sponsor",max_length = 20,default="SPONSOR")
	content = FroalaField()
	created_at = models.DateTimeField(verbose_name="Created Time",auto_now_add=True)
	updated_at = models.DateTimeField(verbose_name="Updated Time",auto_now=True)	
	def date_info(self):
		today = datetime.datetime.now()
		native = self.updated_at.replace(tzinfo=None)
		diff = today-native
		hours = diff.days *24 + diff.seconds//3600
		print(hours)
		return hours
	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render
from .models import *
# Create your views here.
def index(request):
	news = News.objects.all()
	return render(request,'blog/bloglist.html',{'news':news})
def detail_blog(request,tt,id=0):
	news = News.objects.all()
	size = len(news)
	id = int(id)
	if(news):
		news = news[id]
	return render(request,'blog/news.html',{'news':news,'id':id,'size':size-1})

blog/templates/blog/bloglist.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}

<div style="min-height:550px">
  <div id="top-breadcrumb">
    <ol class="breadcrumb" style="background-color:#fff;">
      <li class="breadcrumb-item"><a href="{% url 'main:home'%}" style="color:black">BullrunICO</a></li>
      <li class="breadcrumb-item active">NEWS</li>
    </ol>
  </div>

  <div class="row">
    {% for item in news %}
    <a href="{% url 'blog:home' item.title|slugify|slice:':10' forloop.counter0 %}">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="blog-card">
          <div class="blog-image">
          {%if item.photo %}  
            <img class="img-fluid" src="{% static item.photo %}">
          {%endif%}
          </div>
          <div class="blog-title">
            <a href="#"><p>{{item.title}}</p></a>
          </div>
          <div class="author-date">
            <span id="author">By {{item.author_name}}</span>
            <span id="date">
              {% if item.date_info == 0 %}
                A few moments Ago
              {% else %}
                {{ item.date_info }} Hours Ago
              {% endif %}
            </span>
          </div>
        </div>
      </div>
    </a>
    {% endfor %}    
  </div>
</div>

{% endblock %}

blog/templates/blog/news.html
{% extends "main/base.html" %}
{% block seo%}
<title> {{news.title}} </title>
<meta name="description" content="{{news.content|striptags|slice:':255'}}">
{% endblock %}
{% load static %}
{% block content %}
<div style="min-height:450px">
    <div id="top-breadcrumb">
        <ol class="breadcrumb" style="background-color:#fff;">
            <li class="breadcrumb-item"><a href="{% url 'main:home'%}" style="color:black">BullrunICO</a></li>
            <li class="breadcrumb-item active">NEWS</li>
        </ol>
    </div>

    <!-- Title -->
    <div class="text-uppercase" style="text-align:center">
		<h4>{{news.title}}</h4>
    </div>

    <!-- media : photo or video -->
    <div style="text-align:center;margin-top:30px;">
		{% if news.photo %}
		<div class="col-12" style="margin-bottom:20px;">
			<img class="img-fluid" src="{% static news.photo %}" alt="blog photo">
		</div>
		{% endif %}

		{% if news.movie_url%}
		<div class="row">
			<div class="col-2"></div>
			<div class="col-8" id="ico-video">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="{{ news.movie_url }}" allowfullscreen></iframe>
				</div>
			</div>
			<div class="col-2"></div>
		</div>
		{% endif %}
    </div>

	<!-- contents -->
	<div class="row">
		<div class="col-2"></div>
		<div class="col-8" style="text-align:justify;margin-top:30px;">
			{{ news.content |safe }}
		</div>
		<div class="col-2"></div>
	</div>
    <!-- sponsor or news or analysis -->
    <div class="row" style="margin-top:30px;">
		<div class="col-2"></div>
		<div class="col-4" style="text-align:left">
			<div style="width:100px;height:25px;background-color:rgb(255, 217, 1);text-align:center;box-shadow:2px 4px 2px #000;">
				<p>{{ news.sponsor }}</p>
			</div>
		</div>
		<div class="col-4" style="text-align:right">
			{% if news.date_info == 0%}
				<p> A few moments Ago</p>
			{% else %}
				<p>{{ news.date_info }} Hours Ago</p>
			{% endif %}
		</div>
		<div class="col-2"></div>
	</div>

	<div class="row author">
		<div class="col-2"></div>
		<div class="col-4"></div>
		<div class="col-4">
			<div style="float:right">
				<div class="author-img">
					<img class="img-fluid rounded-circle" src="{% static news.author_image %}" alt="auther photo">
				</div>
				<span>By </span><span style="font-weight:700"> {{news.author_name}}</span>
			</div>
		</div>
		<div class="col-2"></div>
	</div>
	<div style="text-align:center; margin-top:60px;">
		<div>
			<h4>Share our news</h4>
		</div>
		<div style="margin-top:30px;">
			<ul style="list-style:none;">
				<li style="display:inline-block; margin:auto 50px;"><a href="twitter" style="color:black;"><i class="fab fa-twitter"></i><span>   Twitter 33K</span></a></li>
				<li style="display:inline-block; margin:auto 50px;"><a href="telegram" style="color:black;"><i class="fab fa-telegram"></i><span>   Telegram 33K</span></a></li>
				<li style="display:inline-block; margin:auto 50px;"><a href="instagram" style="color:black;"><i class="fab fa-instagram"></i><span>   Instagram 33K</span></a></li>
				<!-- <li style="display:inline-block; margin:auto 50px;"><a href="facebook" style="color:black;"><i class="fab fa-facebook"></i><span>   BullRunICO</span></a></li> -->
			</ul>
		</div>
	</div>
	<!-- ==============================disqus====================================== -->
	<div id="disqus_thread"></div>

	<script>
		/**
		*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
		*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

		var disqus_config = function () {
		this.page.url = 'http://www.bullrunico.com/blog/';  // Replace PAGE_URL with your page's canonical URL variable
		this.page.identifier = 'bullrunico'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
		};

		(function() {
			// DON'T EDIT BELOW THIS LINE
			var d = document, s = d.createElement('script');
			s.src = 'https://bullrun.disqus.com/embed.js';
			s.setAttribute('data-timestamp', +new Date());
			(d.head || d.body).appendChild(s);
		})();
	</script>
	<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

	</div>

{% endblock %}


<!--
<h1> Title : {{news.title}}</h1>
{% if news.photo %}
	<h1> Photo : {{news.photo}}</h1>
{% else%}
	<h1> Photo : No Photo</h1>
{% endif %}
{% if news.movie_url%}
	<h1> Movie : {{news.movie_url}}</h1>
{% else%}
	<h1> Movie : No Movie</h1>
{% endif %}
<h1>Content : {{news.content}}</h1>
{% if news.date_info == 0%}
	<h2> A few moments Ago</h2>
{% else %}
	<h2>{{news.date_info}} Hours Ago</h2>
{% endif %}
-->