blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views
app_name = "blog"
urlpatterns = [
    url(r'^$', views.index,name="initial_home"),
    # url(r'^(?P<tt>\W{0,50})/(?P<id>\d+)', views.detail_blog,name="home"),
    url(r'^(?P<tt>[\w-]+)/(?P<id>\d+)', views.detail_blog,name="home"),
]

ico_proj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('main.urls')),
    url(r'^blog/',include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views
app_name = "main"
urlpatterns = [
    url(r'^$', views.index,name="home"),
    url(r'^detail/(?P<category>\w{0,50})/(?P<name>\w{0,50})/',views.ico_detail,name = "detail"),
    url(r'^category/(?P<category>\w{0,50})/',views.show_by_category,name="category"),
    url(r'^search/',views.search_ico,name="search"),
    url(r'^about/',views.about,name="about"),
    url(r'^adver/',views.adver,name="adver"),
    url(r'^news/',views.news,name="news"),
]

main/models.py
from django.db import models
from django.utils.timesince import timesince
import datetime
import os
# Create your models here.
# from preferences.models import Preferences

# class MyPreferences(Preferences):
#     portal_contact_email = models.EmailField()
#     file = models.FileField()
class ICO(models.Model):	
	# logo_pic = models.CharField(max_length = 200)
	logo_pic = models.FileField(upload_to='Logos')
	name = models.CharField(max_length = 200)
	category = models.CharField(max_length = 200)
	proj_desc = models.CharField(max_length = 200)
	movie_url = models.CharField(max_length = 200)	
	site_url = models.CharField(max_length = 200)	
	whitepaper_url = models.CharField(max_length = 200)
	# token_sale_detail
	ticker = models.CharField(max_length = 200)
	token_type = models.CharField(max_length = 20)
	token_price = models.CharField(max_length = 200)
	token_sale_open = models.DateField()
	token_sale_close = models.DateField()
	fundraising_goal = models.CharField(max_length = 200)
	total_tokens = models.CharField(max_length = 200)
	accepts = models.CharField(max_length = 200)
	interest_type = (        
        ('Not Rated', 'Not Rated'),
        ('Neutral', 'Neutral'),
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),
        ('Sponsored', 'Sponsored'),
    )
	interest = models.CharField(max_length = 10,choices = interest_type,default = 'Not Rated')
	market = models.CharField(max_length = 30,null=True, blank=True)
	def __str__(self):
		return  self.name
	def url_name(self):
		url = self.name.split(".")[0]
		return url
	def date_info(self):
		today = datetime.date.today()
		if(self.token_sale_open>today):	#upcoming
			return self.token_sale_open.strftime("%d %b")
		if(self.token_sale_close<today): #ended
			return self.token_sale_close
		return (self.token_sale_close-today).days
	def status(self):
		today = datetime.date.today()
		if(self.token_sale_open>today):	#upcoming
			return "upcoming"
		if(self.token_sale_close<today): #ended
			return "ended"
		return "active"
	def addition_links(self):
		sl = self.adlink_set.all().filter(link_type="not social")
		return sl
	def social_links(self):
		sl = self.adlink_set.all().filter(link_type="social")
		return sl
	def AdditionalTokenSaleDetails(self):
		return self.atsd_set.all()
	def Reviews(self):
		return self.review_set.all()
	def ScreenShots(self):
		return self.screen_shot_set.all()
	def KYC(self):
		res = self.atsd_set.filter(atsd_name__icontains='Know Your Customer')
		if res:
			res = res[0].atsd_value
		else:
			res = 'No'
		return res
	def white_list(self):
		res = self.atsd_set.filter(atsd_name__icontains='Whitelist')
		if res:
			res = res[0].atsd_value
		else:
			res = 'No'
		return res		
	def participate(self):
		res = self.atsd_set.filter(atsd_name__icontains='participate')
		if res:
			res = res[0].atsd_value
		else:
			res = 'No'
		return res		
	def bounty(self):
		res = self.atsd_set.filter(atsd_name__icontains='bounty')
		if res:
			res = res[0].atsd_value
		else:
			res = 'No'
		return res	
	def bounus(self):
		res = self.atsd_set.filter(atsd_name__icontains='bonus')
		if res:
			res = res[0].atsd_value
		else:
			res = 'No'
		return res
	# available_token_sale = models.CharField(max_length = 20)
	# not_participate = models.CharField(max_length = 200)
	# min_max_person_cap = models.CharField(max_length = 200)
	# token_distribution = models.CharField(max_length = 200)
	
	# bonus = models.CharField(max_length = 200)
	# pre_sale = models.CharField(max_length = 200)
class ATSD(models.Model): # Additional Token Sale Detail
	class Meta:
		verbose_name = "Additional Token Sale Detail"
	ico = models.ForeignKey(ICO, on_delete=models.CASCADE)
	atsd_name = models.CharField(max_length = 200)
	atsd_value = models.CharField(max_length = 200)
	def __str__(self):
		return  self.ico.name
class ADLINK(models.Model):
	class Meta:
		verbose_name = "Additional Link"
	ico = models.ForeignKey(ICO, on_delete=models.CASCADE)
	link_name = models.CharField(max_length = 200)
	link_value = models.CharField(max_length = 200)
	link_str = (('not social','not social'),('social','social'))
	link_type = models.CharField(max_length = 20,choices = link_str)	# social, not_social
	def __str__(self):
		return  self.ico.name
class Advertise(models.Model):
	class Meta:
		verbose_name_plural = "Advertise"
	logo_pic = models.FileField(upload_to='Logos')
	text = models.CharField(max_length = 200)
	url_button = models.CharField(max_length = 200)
			
class REVIEW(models.Model):
	class Meta:
		verbose_name = "Review"
	ico = models.ForeignKey(ICO,on_delete=models.CASCADE)
	review_option = models.CharField(max_length = 200)
	review_option_value = models.CharField(max_length = 200)
	def __str__(self):
		return  self.ico.name
class SCREEN_SHOT(models.Model):
	class Meta:
		verbose_name = "Screen Shot"
	ico = models.ForeignKey(ICO, on_delete=models.CASCADE)
	# pic_url = models.CharField(max_length = 200)
	pic_url = models.FileField(upload_to='ScreenShots')
	def file_name(self):
		tmp_url = os.path.basename(self.pic_url.url)
		name, extension = os.path.splitext(tmp_url)
		return name
	def __str__(self):
		return  self.ico.name

main/views.py
from django.shortcuts import render,get_object_or_404
from .models import *
import datetime
import requests

# Create your views here.

def index(request):
	icos = ICO.objects.all()
	today = datetime.datetime.today()
	active_icos = icos.filter(token_sale_open__lte=today,token_sale_close__gte=today)
	upcoming_icos = icos.filter(token_sale_open__gt=today)
	ended_icos = icos.filter(token_sale_close__lt=today)
	return render(request,'main/main.html',{'active_icos':active_icos,'upcoming_icos':upcoming_icos,'ended_icos':ended_icos})

def ico_detail(request,category,name):
	today = datetime.datetime.today()
	icos = ICO.objects.all()
	ico = get_object_or_404(ICO,name__icontains=name)
	ico_id = ico.id	
	active_icos = icos.filter(token_sale_open__lte=today,token_sale_close__gte=today)
	upcoming_icos = icos.filter(token_sale_open__gt=today)
	ended_icos = icos.filter(token_sale_close__lt=today)
	other_icos = []
	if ico.status() == "active":
		other_icos = active_icos.exclude(pk = ico_id)
	elif ico.status() == "upcoming":
		print("upcoming")
		other_icos = upcoming_icos.exclude(pk = ico_id)
	elif ico.status() == "ended":
		other_icos = ended_icos.exclude(pk = ico_id)
	print(other_icos)
	return render(request,'main/ico_detail.html',{'ico':ico,'other_icos':other_icos})

def search_ico(request):
	if request.method == 'GET': # this will be GET now      
		ico_name =  request.GET.get('search_ico') # do some research what it does    
		if(ico_name is not None):
			# try:
			icos = ICO.objects.filter(name__icontains=ico_name) # filter returns a list so you might consider skip except part
			return render(request,"main/search.html",{'icos':icos,'search_name':ico_name})
	return render(request,"main/search.html",{"icos":None,"search_name":""})

def show_by_category(request,category):
	category_icos = []
	icos = ICO.objects.all()
	today = datetime.datetime.today()
	category_type = category
	if(category == "active"):
		category_icos = icos.filter(token_sale_open__lte=today,token_sale_close__gte=today)
	elif(category == "upcoming"):
		category_icos = icos.filter(token_sale_open__gt=today)
	elif(category=="ended"):
		category_icos = icos.filter(token_sale_close__lt=today)
	else:
		category_type = "Undefined Category"
	return render(request,'main/category.html',{'icos':category_icos,'category_type':category_type})

def about(request):
	return render(request,'main/about.html')

def adver(request):
	return render(request,'main/adver.html')

def news(request):
	return render(request,'main/news.html')

main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
<div id="top-breadcrumb">
    <ol class="breadcrumb" style="background-color:#fff;">
        <li class="breadcrumb-item"><a href="{% url 'main:home'%}" style="color:black">BullrunICO</a></li>
        <li class="breadcrumb-item active">About</li>
    </ol>
</div>
<div style="margin-top:40px;">
    <div style="text-align:center;">
        <h4>ABOUT US</h4>
    </div>
    <div style="width:80%; margin:20px auto; text-align:justify;">
        BullrunICO aims to be the leading database and information source when it comes to ICO investing. Our primary goal is to bring real value to our audience and community, providing accurate and transparent data to our customers as also right investment strategies on how to build a strong portfolio from the ground up so you can overcome any circumstances it may come to you as an investor.  At BullRunICo we only list ICO's that have been approved by general community advisors, popular ICO's investment websites and also our investigation team. Please, be noticed that we strongly advise you to do your research and never rely on just one source of information no matter how good they are or have been in the past, always do your research.
    </div>
    {% load custom_tags %}
    {% contact %}
</div>

{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block seo %}
    {% endblock seo %}  
    <title>ICO Details of Page Title</title>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">


    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    {% load custom_tags %}
</head>
<body>
    <div>
        <header> 
            <!-- abs banner -->
            {% ads %}
<!--             <div class="text-center" style="background-color: yellow; box-shadow: none; padding-top:5px;padding-bottom:5px;">
                <div style="display:inline-block">
                    <a href="https://copytrack.io/?utm_source=icodrops&amp;utm_medium=banner&amp;utm_campaign=topbanner" target="_blank">
                        <img class="ad-logo" src="{% static 'bitcoin.png' %}" alt="the-top" style="height: 30px;">
                    </a>
                </div>
                <div class="the-top-banner-text"  style="display:inline-block">
                 <span class="ad-description" style="color:rgb(0, 0, 0);"> COPYTRACK –  JOIN THE    COPYRIGHT REVOLUTION | $10M+ ALREADY RAISED</span>
                    <span>
                        <a class="btn btn-outline-success btn-sm" href="https://copytrack.io/?utm_source=icodrops&amp;utm_medium=banner&amp;utm_campaign=topbanner" target="_blank" rel="nofollow" style="vertical-align: 2px; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0);">SECURE BONUS NOW</a>

                    </span>
                </div>
            </div> -->
            <!-- abs banner end -->

            <div class="container">
                <div class="row" id="top-menubar">
                    <div class="col-2">
                        <a href="{% url 'main:home' %}" id="main-logo">
                            <img id="logo" src="{% static 'bull_white.png' %}" alt="Logo">
                        </a>
                    </div>
                    <div class="col-3 main-search">
                        <form class="form-inline" method="get" action="{% url 'main:search' %}">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <button class="btn btn-sm" id="search-btn" type="submit"><i class="fa fa-search"></i></button>
                                </div>
                                <input id="mysearch" class="form-control" type="text" name="search_ico" placeholder="Search ICO" aria-label="Search" style="padding-left: 20px; border-radius: 40px;">
                                
                            </div>
                        </form>
                    </div>
                    <div class="col-7 main-menu-container closed" style="padding-right:0">
                        <div class="main-menu-toggle">
                            <p>Menu</p>
                            <button><span> </span></button>
                        </div>
                        <ul class="main-menu">
                            <li class="menu-item">
                                <a class="" href="{% url 'main:category' 'active' %}"><strong>ACTIVE ICO</strong></a>
                            </li>
                            <li class="menu-item">
                                <a class="" href="{% url 'main:category' 'upcoming' %}"><strong>UPCOMING ICO</strong></a>
                            </li>
                            <li class="menu-item">
                                <a class="" href="{% url 'main:category' 'ended' %}"><strong>ENDED ICO</strong></a>
                            </li>
                            <li class="menu-item">
                                <a class="" href="{% url 'main:category' 'stats' %}"><strong>ICO STATS</strong></a>
                            </li>
                            <li class="menu-item">
                                <a class="" href="{% url 'blog:initial_home'%}"><strong>NEWS</strong></a>
                            </li>
                            <li class="menu-item" id="menu-search">
                                <form class="form-inline" method="get" action="{% url 'main:search' %}">
                                    <div>
                                        <button id="buttion-in-menu" type="submit" hidden><i class="fa fa-search"></i></button>
                                        <span><i class="fa fa-search"></i></span>
                                        <input id="search-in-menu" type="text" name="search_ico" placeholder="Search ICO" aria-label="Search" size="15">
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </header><!-- header end -->

        <div class="container">
            <div class="main-page">
                <div class="row">

                    {% btc_eth %}
                    <div class="col-8">
                        <ul class="top-social-link">
                            <li class="soc-link"><a href="https://twitter.com/BullRunICO" target="_blank"><i class="fab fa-twitter"></i><span>Twitter</span></a></li>
                            <li class="soc-link"><a href="https://t.me/bullrunico" target="_blank"><i class="fab fa-telegram"></i><span>Telegram</span></a></li>
                            <li class="soc-link"><a href="https://medium.com/@bullrunICO" target="_blank"><i class="fab fa-medium"></i><span>Medium</span></a></li>
                            <li class="soc-link"><a href="https://steemit.com/@bullrun" target="_blank"><i class="fab fa-steam"></i><span>Steem</span></a></li>
                            <!-- <li class="soc-link"><a href="instagram"><i class="fab fa-instagram"></i><span>Instagram</span></a></li> -->
                        </ul>
                    </div>
                </div>
            </div>

            {% block content %}
            {% endblock content %}  
            
            <!-- discus -->

        </div>
        <!-- footer -->
        <div class="footer-section">
            <div class="container" style="background-color:black; padding-right:20px;padding-left:20px;">
                <div class="row" id="footer-body">
                    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        <img src="{% static 'bull_black.png' %}" alt="LOGO" style="width:130px;">
                        <div style="margin-top:10px; font-size:14px; color:rgb(152, 153, 153);">
                            Made to bring transparency to 
                            our ICO investment ecosystem. 
                            BullRunICO is not affiliated or 
                            receives any incentive from 
                            ICO projects or blockchain 
                            companies. We also do not give any 
                            investment advice, we only provide 
                            information and data to our growing 
                            community. 
                        </div>
                        <div style="margin-top:20px; font-size:15px; color:rgb(152, 153, 153);">
                            All rights reserved © 2018 BullRunICO
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                        <div>
                            <ul style="list-style:none;">
                                <li><a href="{% url 'main:category' 'active' %}" style="color:rgb(152, 153, 153);">ACTIVE ICO</a></li>
                                <li><a href="{% url 'main:category' 'upcoming' %}" style="color:rgb(152, 153, 153);">UPCOMING ICO</a></li>
                                <li><a href="{% url 'main:category' 'ended' %}" style="color:rgb(152, 153, 153);">ENDED ICO</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                        <div>
                            <ul style="list-style:none;">
                                <li><a href="{% url 'main:about' %}" style="color:rgb(152, 153, 153);">ABOUT US</a></li>
                                <li><a href="{% url 'main:adver' %}" style="color:rgb(152, 153, 153);">ADVERTISING</a></li>
                                <li><a href="{% url 'blog:initial_home' %}" style="color:rgb(152, 153, 153);">NEWS</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6">
                        <div>
                            <ul style="list-style:none;">
                                <li><a href="twitter" style="color:rgb(152, 153, 153);"><i class="fab fa-twitter"></i><span>   Twitter</span></a></li>
                                <li><a href="telegram" style="color:rgb(152, 153, 153);"><i class="fab fa-telegram"></i><span>   Telegram</span></a></li>
                                <li><a href="instagram" style="color:rgb(152, 153, 153);"><i class="fab fa-facebook"></i><span>   Facebook</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div><!-- page end -->
    <script>
        $(document).ready(function(){
            var i;
		    $('.main-menu-toggle').click(function(){

                if($('.main-menu-toggle').parent().hasClass("closed")) {

                    $('.main-menu-toggle').parent().removeClass("closed").addClass("opened");

                    $('.main-menu-toggle > p').text("Close");

                }else {

                    $('.main-menu-toggle').parent().removeClass("opened").addClass("closed");

                    $('.main-menu-toggle > p').text("Menu");

                }
            });   
	    });
    </script>
    <script id="dsq-count-scr" src="//bullrun.disqus.com/count.js" async></script>
</body>
</html>

main/templates/main/main.html
{% extends "main/base.html" %}
{%load static%}
{%block content%}
	<div class="row" style="display:flex;min-height:500px;">
		<div class="col-md-12 col-lg-4">
			<div class="category-table-header">
				<h5 style="text-align:center; font-weight:bold">
					<a href="{%url 'main:category' 'active'%}">ACTIVE ICO</a>
				</h5>
			</div>
			<div class="category1">
				{% for ico in active_icos %}
					<a id="n-color" href="{%url 'main:detail' ico.status ico.url_name %}">
						<div class="ico-card main-card">
							<div class="ico-card-row">
								<div class="ico-card-icon" style="display:inline-block">
									<img class="rounded-circle" src="{% static ico.logo_pic %}" alt="LOGO" width="60">
								</div>
								<div class="ico-card-main-info" style="display:inline-block;width:auto">
									<h5>
										{{ico.name}}
									</h5>
									<div class="ico-category-name">
										{{ico.category}}
									</div>
									<div class="goal-in-card">
										<span class="curency">${{ ico.fundraising_goal }}</span>
										<span>/{{ ico.total_tokens }}</span>
										<span></span>
									</div>
								</div>
							</div>
							<div class="interest" style="display:inline-block;">
								<span>{{ ico.interest }}</span>
							</div>
							<div class="date" style="float:right;">
								<span>{{ ico.date_info}}d</span>
							</div>
						</div>
					</a>
				{% endfor %}
				<a class="allview" href="{% url 'main:category' 'active' %}">
					<div class="ico-viewall">
						<span>VIEW ALL </span>
						<span> {{active_icos|length}}</span>
						<span>ACTIVE ICO</span>
						<span><i class="fas fa-arrow-right"></i></span>
					</div>
				</a>
			</div>
		</div>
		<div class="col-md-12 col-lg-4">
			<div class="category-table-header">
				<h5 style="text-align:center; font-weight:bold">
					<a href="{% url 'main:category' 'upcoming' %}">UPCOMING ICO</a>
				</h5>
			</div>
			<div class="category1">
				{% for ico in upcoming_icos %}
					<a id="n-color" href="{%url 'main:detail' ico.status ico.url_name%}">
						<div class="ico-card main-card">
							<div class="ico-card-row">
								<div class="ico-card-icon" style="display:inline-block;">
									<img class="rounded-circle" src="{% static ico.logo_pic %}" alt="LOGO" width="60" height="60">
								</div>
								<div class="ico-card-main-info" style="display:inline-block;">
									<h5>
										{{ico.name}}
									</h5>
									<div class="ico-category-name">
										{{ico.category}}
									</div>
									<div class="goal-in-card">
										<span class="curency">${{ ico.fundraising_goal }}</span>
										<span>/{{ ico.total_tokens }}</span>
										<span></span>
									</div>
								</div>
							</div>
							<div class="interest" style="display:inline-block;">
								<span>{{ ico.interest }}</span>
							</div>
							<div class="date" style="float:right">
								<span>{{ ico.date_info}} left</span>
							</div>
						</div>
					</a>
				{% endfor %}
				<a class="allview" href="{% url 'main:category' 'upcoming' %}">
					<div class="ico-viewall">
						<span>VIEW ALL </span>
						<span> {{upcoming_icos|length}}</span>
						<span>UPCOMING ICO</span>
						<span><i class="fas fa-arrow-right"></i></span>
					</div>
				</a>
			</div>
		</div>
		<div class="col-md-12 col-lg-4">
		<div class="category-table-header">
				<h5 style="text-align:center; font-weight:bold">
					<a href="{% url 'main:category' 'ended' %}">ENDED ICO</a>
				</h5>
			</div>
			<div class="category1">
				{% for ico in ended_icos %}
					<a id="n-color" href="{%url 'main:detail' ico.status ico.url_name%}">
						<div class="ico-card main-card">
							<div class="ico-card-row">
								<div class="ico-card-icon" style="display:inline-block;">
									<img class="rounded-circle" src="{% static ico.logo_pic %}" alt="LOGO" width="60" height="60">
								</div>
								<div class="ico-card-main-info" style="display:inline-block;">
									<h5>
										{{ico.name}}
									</h5>
									<div class="ico-category-name">
										{{ico.category}}
									</div>
									<div class="goal-in-card">
										<span class="curency">${{ ico.fundraising_goal }}</span>
										<span>/{{ ico.total_tokens }}</span>
										<span></span>
									</div>
								</div>
							</div>
							<div class="interest" style="display:inline-block;">
								<span>{{ ico.interest }}</span>
							</div>
							<div class="date" style="float:right">
								<span>{{ ico.date_info}} Ended</span>
							</div>
						</div>
					</a>
				{% endfor %}
				<a class="allview" href="{% url 'main:category' 'ended' %}">
					<div class="ico-viewall">
						<span>VIEW ALL </span>
						<span> {{ended_icos|length}}</span>
						<span>ENDED ICO</span>
						<span><i class="fas fa-arrow-right"></i></span>
					</div>
				</a>				
			</div>
		</div>
	</div>
{%endblock content%}